# data collection folders
RECENT_SEARCH_TWITTER_S3_DATA_COLLECTION_FOLDER: "data_collection/recent_search_twitter/"
# test folders
RECENT_SEARCH_TWITTER_S3_TEST_DATA_COLLECTION_FOLDER: "data_collection/recent_search_twitter_test/"
analysis_date_stamp: "20231221"
production: "true"
